#!/system/bin/sh
##Governors Tweaks
#

#Tweak BOOSTEDassV2
echo "600000" > /sys/devices/system/cpu/cpufreq/boostedASSv2/awake_ideal_freq
echo "300000" > /sys/devices/system/cpu/cpufreq/boostedASSv2/sleep_ideal_freq
echo "600000" > /sys/devices/system/cpu/cpufreq/boostedASSv2/sleep_wakeup_freq
echo "75" > /sys/devices/system/cpu/cpufreq/boostedASSv2/max_cpu_load
echo "45" > /sys/devices/system/cpu/cpufreq/boostedASSv2/min_cpu_load
echo "0" > /sys/devices/system/cpu/cpufreq/boostedASSv2/ramp_up_step
echo "0" > /sys/devices/system/cpu/cpufreq/boostedASSv2/ramp_down_step
echo "24000" > /sys/devices/system/cpu/cpufreq/boostedASSv2/up_rate_us
echo "99000" > /sys/devices/system/cpu/cpufreq/boostedASSv2/down_rate_us
echo "2" > /sys/devices/system/cpu/cpufreq/boostedASSv2/sample_rate_jiffies

#Tweak smartassV2
echo "600000" > /sys/devices/system/cpu/cpufreq/smartass/awake_ideal_ freq
echo "300000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_ideal_ freq
echo "600000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_wakeup_ freq
echo "75" > /sys/devices/system/cpu/cpufreq/smartass/max_cpu_load
echo "45" > /sys/devices/system/cpu/cpufreq/smartass/min_cpu_load
echo "0" > /sys/devices/system/cpu/cpufreq/smartass/ramp_up_step
echo "0" > /sys/devices/system/cpu/cpufreq/smartass/ramp_down_step
echo "24000" > /sys/devices/system/cpu/cpufreq/smartass/up_rate_us
echo "99000" > /sys/devices/system/cpu/cpufreq/smartass/down_rate_us

##Pegasus
echo "80" > /sys/devices/system/cpu/cpufreq/pegasusq/up_threshold
echo "70" > /sys/devices/system/cpu/cpufreq/pegasusq/up_threshold_ at_min_freq
echo "40000" > /sys/devices/system/cpu/cpufreq/pegasusq/sampling_rate
echo "2" > /sys/devices/system/cpu/cpufreq/pegasusq/sampling_ down_factor
echo "5" > /sys/devices/system/cpu/cpufreq/pegasusq/down_differential
echo "40" > /sys/devices/system/cpu/cpufreq/pegasusq/freq_step
echo "300000" > /sys/devices/system/cpu/cpufreq/pegasusq/freq_for_ responsiveness
echo "10" > /sys/devices/system/cpu/cpufreq/pegasusq/cpu_up_rate
echo "20" > /sys/devices/system/cpu/cpufreq/pegasusq/cpu_down_rate
echo "300000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_ 1_1
echo "300000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_ 2_0
echo "350" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_1_1
echo "200" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_2_0
echo "0" > /sys/devices/system/cpu/cpufreq/pegasusq/ignore_nice_load
echo "1" > /sys/devices/system/cpu/cpufreq/pegasusq/io_is_busy
echo "0" > /sys/devices/system/cpu/cpufreq/pegasusq/max_cpu_lock
echo "0" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_lock

#ondemand
echo "70" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
echo "40000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
echo "2" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
echo "15" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential

#conservative
echo "60" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold
echo "40000" > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate
echo "5" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor
echo "20" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold
echo "25" > /sys/devices/system/cpu/cpufreq/conservative/freq_step

#interactive
echo "95" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
echo "1000000" > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
echo "10000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate

#hotplug
echo "35" > /sys/module/pm_hotplug/parameters/loadl
echo "75" > /sys/module/pm_hotplug/parameters/loadh
echo "50" > /sys/module/pm_hotplug/parameters/loadl_scroff
echo "100" > /sys/module/pm_hotplug/parameters/loadh_scroff
echo "100" > /sys/module/pm_hotplug/parameters/rate
echo "400" > /sys/module/pm_hotplug/parameters/rate_cpuon
echo "400" > /sys/module/pm_hotplug/parameters/rate_scroff
echo "800000" > /sys/module/pm_hotplug/parameters/freq_cpu1on

